<?php
/** @var $form \Auth\Form\LoginForm */
$form = $this->form;
$form->prepare();
?>

<div class="container">
    <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card my-5">
                <div class="card-body">
                    <h5 class="card-title text-center">Login</h5>
                    <?= $this->form()->openTag($form); ?>
                        <div class="form-label-group">
                            <?= $this->formLabel($form->get('email')); ?>
                            <?= $this->formElement()->render($form->get('email')); ?>
                        </div>
                        <div class="form-label-group">
                            <?= $this->formLabel($form->get('password')); ?>
                            <?= $this->formElement()->render($form->get('password')); ?>
                        </div>
                        <?= $this->formElement($form->get('submit')); ?>
                    <?= $this->form()->closeTag(); ?>
                    <div>
                        <?php
                        foreach ($this->errors as $error) {
                            echo "<div class='alert-danger mt-3 p-1'>{$error->getMessage()}</div>";
                        }
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
