<?php
/** @var $form \Auth\Form\LoginForm */
$form = $this->form;
$form->prepare();
?>

<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-7 col-lg-5 mx-auto">
            <div class="card my-5">
                <h2 class="card-header text-center">Login</h2>
                <div class="card-body">
                    <?= $this->form()->openTag($form); ?>
                        <div class="form-label-group">
                            <?= $this->formLabel($form->get('email')); ?>
                            <?= $this->formElement()->render($form->get('email')); ?>
                        </div>
                        <div class="form-label-group">
                            <?= $this->formLabel($form->get('password')); ?>
                            <?= $this->formElement()->render($form->get('password')); ?>
                        </div>
                        <?= $this->formElement($form->get('submit')); ?>
                    <?= $this->form()->closeTag(); ?>
                    <div>
                        <?php
                        foreach ($this->errors as $error) {
                            echo "<div class='alert-danger mt-3 p-1'>{$error->getMessage()}</div>";
                        }
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12 mx-auto">
            <div class="card my-5">
                <h2 class="card-header">Content</h2>
                <div class="card-body">
                    <ul>
                    <?php
                    if (is_countable($this->content) && count($this->content) > 0) {
                        foreach ($this->content as $content) /** @var $content \Application\Entity\Content */ {
                            echo "<li>{$content->getTitle()}: {$content->getText()} </li>";
                        }
                    } else {
                        echo "No content yet, login and add some!";
                    }
                    ?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
