<?php
/** @var $username string */
/** @var $form \Application\Form\ContentForm */
$form = $this->form;
$form->prepare();
?>
<div class="jumbotron">
    <h1 class="display-4">Welcome <?= $username ?>!</h1>
</div>

<div class="card-deck">
    <div class="card">
        <h2 class="card-header">Add some content</h2>
        <div class="card-body">
            <?= $this->form()->openTag($form); ?>
            <div class="form-label-group">
                <?= $this->formLabel($form->get('title')); ?>
                <?= $this->formElement()->render($form->get('title')); ?>
            </div>
            <div class="form-label-group">
                <?= $this->formLabel($form->get('text')); ?>
                <?= $this->formElement()->render($form->get('text')); ?>
            </div>
            <?= $this->formElement($form->get('submit')); ?>
            <?= $this->form()->closeTag(); ?>
            <?php
            foreach ($this->messages as $message) {
                echo "<div class='alert-success mt-3 p-1'>{$message}</div>";
            }
            ?>
            <?php
            foreach ($this->error as $error) {
                echo "<div class='alert-success mt-3 p-1'>{$error}</div>";
            }
            ?>
        </div>
    </div>
</div>
